name: easy-openvpn-server
title: Easy OpenVPN Server
version: "0.1"
summary: A dead-simple OpenVPN server.
description: | 
  A dead-simple OpenVPN server.
license: Apache-2.0

base: core18
grade: stable
confinement: strict

passthrough:
  system-usernames:
    snap_daemon: shared

apps:
  tcp-server:
    daemon: simple
    command: usr/sbin/openvpn --config $SNAP_USER_DATA/tcp-server.conf --cd $SNAP_USER_DATA
    command-chain:
      - bin/run.sh
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control
    environment:
      LD_PRELOAD: "$SNAP/wraplib.so"
  udp-server:
    daemon: simple
    command: usr/sbin/openvpn --config $SNAP_USER_DATA/udp-server.conf --cd $SNAP_USER_DATA
    command-chain:
      - bin/run.sh
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control
    environment:
      LD_PRELOAD: "$SNAP/wraplib.so"
  status:
    command: bin/status.sh
  openvpn:
    command: usr/sbin/openvpn --config $SNAP_USER_DATA/tcp-server.conf --cd $SNAP_USER_DATA
    command-chain:
      - bin/run.sh
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control
    environment:
      LD_PRELOAD: "$SNAP/wraplib.so"
  easy-openvpn-server:
    command: bin/setup.py
    plugs:
      - network    
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

hooks:
  configure:
    plugs:
      - network
      - network-control
  connect-plug-network-control: {}
  connect-plug-firewall-control: {}
  

parts:
  openvpn:
    plugin: nil
    stage-packages:
      - openvpn
      - iptables
      - libatm1
  scripts:
    plugin: dump
    source: scripts
    organize:
      "*": bin/
  scripts-dependencies:
    plugin: python
    source: easy-openvpn-server
    requirements:
      - requirements.txt 
    stage-packages:
      - facter
      # Dependencies for building `cryptography` on non-amd64 systems.
      - libffi-dev
      - libssl-dev
  templates:
    plugin: dump
    source: templates
    organize:
      "*": templates/
  setgroups-patch:
    plugin: make
    source: setgroups-patch
    build-packages:
      - build-essential
